### ISSUE TITLE
辛苦修改下博客中的 Google Analytics 的代码吧

### ISSUE THREAD

**Issue by leovan** [Windxy/windxy.github.io#1]
辛苦修改下博客中的 Google Analytics 的代码吧，用的还是我网站中的 G-RJC7CCKE67，已经看到贵站的浏览数据跑到我的 Google Analytics 中了。

**Comment by Windxy** [comment]
非常抱歉在参考使用您的网站时，忘记删除相关脚本信息，为此给您带来诸多不便，现已经将所有 Google Analytics&nbsp;相关的脚本代码删除，非常抱歉！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Windxy/windxy.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 晚上9:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Windxy/windxy.github.io] 辛苦修改下博客中的 Google Analytics 的代码吧 (Issue #1)





 
辛苦修改下博客中的 Google Analytics 的代码吧，用的还是我网站中的 G-RJC7CCKE67，已经看到贵站的浏览数据跑到我的 Google Analytics 中了。
